### ISSUE TITLE
bash completion 

### ISSUE THREAD

**Issue by bjartek** [openshift-evangelists/oc-cluster-wrapper#17]
Add bash completions so that it is easier to use the tool. 

I can look into this if you want me to.

**Comment by jorgemoralespou** [comment]
@bjartek Can you add completions to the base script and not as a separate file, so that it can be added with:

oc-cluster completion bash

Similar to this: http://kubernetes.io/docs/user-guide/kubectl/kubectl_completion/

Then it will be easier to maintain.

Thanks.

**Comment by bjartek** [comment]
./oc-cluster completion bash | sudo tee /usr/local/etc/bash_completion.d/oc-cluster works on my mac now
