### ISSUE TITLE
Not possible to set the public hostname on linux

### ISSUE THREAD

**Issue by siamaksade** [openshift-evangelists/oc-cluster-wrapper#31]
Setting the public hostname via `OC_CLUSTER_PUBLIC_HOSTNAME` is ignored by the script and it's overridden by setting it to `$(which-ip docker0)` in the `plugins` branch: 
https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/plugins/oc-cluster#L28

**Comment by jorgemoralespou** [comment]
@siamaksade are you testing on mac, linux or both?

**Comment by siamaksade** [comment]
This happens on linux. I have tested on CentOS 7

**Comment by jorgemoralespou** [comment]
This should be fixed. Can you test. Also plugins branch is merged, so many enhancements done here.

**Comment by csrwng** [comment]
@jorgemoralespou I tried it on my linux machine (RHEL 7) and I ran into this as well. I cannot override the public hostname
