### ISSUE TITLE
How to add nodes to the cluster created with oc-cluster up?

### ISSUE THREAD

**Issue by umaxfun** [openshift-evangelists/oc-cluster-wrapper#35]
How to add nodes to the cluster created with `oc-cluster up`? 

Can I just use `oc-cluster up` on another host and  link it to the first host in some way? Official docs seem too complex after `oc-cluster up`s magic :)

**Comment by jorgemoralespou** [comment]
@umaxfun no, you can't. "oc cluster up" and this wrapper are meant to create an all-in-one cluster, hence there is no way to create a multinode cluster and it will not be.
For that you'll need to use ansible way of installing openshift.
