### ISSUE TITLE
Script uses --host-pv-dir instead of --host-volumes-dir

### ISSUE THREAD

**Issue by wkulhanek** [openshift-evangelists/oc-cluster-wrapper#45]
When spinning up a cluster the script writes the start command into ..../profiles/name/run. But it writes --host-pv-dir which is not a valid option. Therefore subsequent cluster starts fail.

Tested on oc 3.4.0.39 and 3.4.0.40.

**Comment by jorgemoralespou** [comment]
@wkulhanek have you updated the tool? This should have been fixed already.

Can you paste the output of:

````
git show --oneline -s
````

**Comment by jorgemoralespou** [comment]
@wkulhanek Just validated that it works.

This is my output:

`````
$ oc-cluster up ocp-34 --image='registry.access.redhat.com/openshift3/ose' --version='v3.4.0.40'
[INFO] Running a new cluster
oc cluster up --public-hostname 127.0.0.1 --routing-suffix apps.lcup --host-data-dir /Users/jmorales/.oc/profiles/ocp-34/data --host-config-dir /Users/jmorales/.oc/profiles/ocp-34/config --use-existing-config -e TZ=CET --image=registry.access.redhat.com/openshift3/ose --version=v3.4.0.40
````

**Comment by wkulhanek** [comment]
Did pull the latest and sure enough it works. Thought I had done that before but I guess not. :-) Thanks for checking.
