### ISSUE TITLE
hostPath volumes needs write (777) permission for random userid

### ISSUE THREAD

**Issue by rafaeltuelho** [openshift-evangelists/oc-cluster-wrapper#50]
Trying to install nexus plugin fails during Nexus' POD startup. When nexus tries to write on `/nexus-data` PV it receives a Pemission Denied error. It only works if you give a 777 on `~/.oc/volumes/nexus-data`.

I had to enable hostPath Volume Plug-in on global scc as described in [1]

[1] https://docs.openshift.com/enterprise/3.0/admin_guide/manage_scc.html#use-the-hostpath-volume-plugin

**Comment by rafaeltuelho** [comment]
same for gitlab...

Permission Denied for postgres, redis and gitlab PODs' hostPath mounted PVs....

**Comment by jorgemoralespou** [comment]
I introduced a bug not too long ago. Fixed as I reverted permissions to 777 instead of 770.

@rafaeltuelho Sorry for that.
