### ISSUE TITLE
oc-cluster on VM startup

### ISSUE THREAD

**Issue by bmaltais** [openshift-evangelists/oc-cluster-wrapper#75]
Hi. Great work by the way ;-)

I am trying to run oc-cluster on vm startup so users don't have to manually start the service via SSH... long story short I am trying to create an Openstack heat template that would deliver a fully functional openshift dev vm with no user intervention...

My issue is that running oc cluster up or oc-cluster up result in containers breifly starting on the VM and stoping soon after.

If I run the same command as a user via ssh everything work fine.

I created an openshift.service under /etc/systemd/system to start/stop oc cluster...

Any advice on doing this? I know it is not related to a bug or issue with the wrapper but I tought you might have an idea on how to get this to work.

Many thanks!

**Comment by jorgemoralespou** [comment]
@bmaltais Hi, I haven't had this usecase before, as I mostly start up clusters in my local laptop, and that's it.

I would guess that using an openshift.service is the right way to go (making sure you have docker and the docker insecure registry properly configured).

If you make it work, I would happily accept a PR to the README explaining the use case, and even a sample openshift.service file. 

Keep in mind this tool was created for development purposes where you will most probably start different profiles at will, but definitely can be used.

I'll close the issue. Feel free to reopen, or open a new one if you want something more.
