### ISSUE TITLE
Using downstream oc doesn't work

### ISSUE THREAD

**Issue by e-minguez** [openshift-evangelists/oc-cluster-wrapper#9]
Related to this issue https://bugzilla.redhat.com/show_bug.cgi?id=1380555
Also, it would be nice to have some kind of flag to use the downstream or the upstream oc binary in order to create OCP/Origin clusters.

**Comment by bjartek** [comment]
What if we define an env var OC as which oc, and use that in the code. 

Then you could call it with

OC=/path/to/downstream/oc oc-cluster example up

Would that work?
